services:
  - type: web
    name: txting-demo
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    staticPublishPath: ./txting-app/dist/txting-app/browser